[terminal]
vt = 1

[default_session]
command = "tuigreet --cmd 'uwsm app -- Hyprland' --theme 'border=magenta;text=cyan;prompt=green;time=red;action=blue;button=yellow;container=black;input=red'"
user = "greeter"